apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: busy-mule-nodejs 
  janus-idp.io/tekton: busy-mule-nodejs
  backstage.io/kubernetes-id: busy-mule-nodejs
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: busy-mule-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  