apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: busy-mule-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: busy-mule-nodejs 
  name: busy-mule-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: busy-mule-nodejs 
